# Generated by Django 3.1.6 on 2021-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_value', models.IntegerField(blank=True, null=True)),
                ('channel_name', models.TextField(blank=True, null=True)),
                ('parent_network', models.TextField(blank=True, null=True)),
                ('market', models.TextField(blank=True, null=True)),
                ('channel_id', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('ui_flag', models.IntegerField(blank=True, db_column='UI_Flag', null=True)),
                ('barc_id', models.IntegerField(blank=True, null=True)),
                ('barc_code', models.IntegerField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('abbreviation', models.TextField(blank=True, null=True)),
                ('feed_if', models.IntegerField(blank=True, null=True)),
                ('aop_bucket_flag', models.IntegerField(blank=True, null=True)),
                ('project_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel_info',
                'managed': False,
            },
        ),
    ]
