# Generated by Django 3.1.6 on 2021-02-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='DATE', null=True)),
                ('currency_type', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.TextField(blank=True, null=True)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency_types',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ChannelInfo',
        ),
    ]
